sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: ipv4_address
      - type: processor_use
      - type: last_boot

  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'BioGeekJoey/hassio-config'
        name: github home assistant repo

  - platform: moon

  - platform: airvisual
    api_key: !secret airvisual_api_key

#   - platform: speedtest
#     monitored_conditions:
#       - ping
#       - download
#       - upload