---
sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: ipv4_address
      - type: processor_use
      - type: last_boot

  - platform: moon

  - platform: airvisual
    api_key: !secret airvisual_api_key

  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"

speedtestdotnet:

fastdotcom:
