---
shelly:
  discovery: true
  sensors:
    - all
  devices:
    - id: '227968'
      name: spotjes Joël
      light_switch: true
    - id: '2285F5'
      name: spotjes washok
      light_switch: true
    - id: '2673E0'
      name: wasmachine
    - id: '267A4A'
      name: droger

sensor:
  - platform: template
    sensors:
      wasmachine_status:
        friendly_name: wasmachine
        value_template: {{ 'klaar' if states.sensor.shelly_shplg_s_2673e0_consumption.state|float <= 2 else '' }}

      droger_status:
        friendly_name: droger
        value_template: {{ 'klaar' if states.sensor.shelly_shplg_s_267a4a_consumption.state|float <= 2 else '' }}