---
shelly:
  discovery: true
  cloud_auth_key: !secret shelly_cloud_key
  cloud_server: !secret shelly_cloud_url
  igmp_fix: true
  sensors:
    - all
  devices:
    - id: '227968'
      name: spotjes Joël
      light_switch: true
    - id: '2285F5'
      name: spotjes washok
      light_switch: true
    - id: '2673E0'
      name: wasmachine
    - id: '267A4A'
      name: droger
    - id: '2678A9'
      name: ups
    - id: '04116E'
      name: itho box
    - id: '125522'
      name: rolluik Joël

sensor:
  - platform: template
    sensors:
      wasmachine_status:
        friendly_name: wasmachine
        value_template: >-
          {{ 'klaar' if states.sensor.shelly_shplg_s_2673e0_consumption_2.state|float <= 2 else 'bezig' }}

      droger_status:
        friendly_name: droger
        value_template: >-
          {{ 'klaar' if states.sensor.shelly_shplg_s_267a4a_consumption_2.state|float <= 2 else 'bezig' }}
