---
repository:
  description: ':house: Home Assistant config.'
  homepage: https://github.com/BioGeekJoey/
  topics: homeassistant-config, home-assistant-config, home-assistant, homeassistant, hass, hassio, iot, internetofthings, internet-of-things, automation, homeautomation, home-automation
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  branches:
    - name: master
      protection:
        required_pull_request_reviews:
          # required_approving_review_count: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
        required_status_checks:
          strict: false
          contexts: []
        enforce_admins: false
