dist: xenial:latest

language: python

python:
  - "latest"
  - "3.7.4"
  - "3.5.5"

env:
  - HASS='homeassistant'
  - HASS='--pre homeassistant'
  
matrix:
  allow_failures: 
    - python: "latest"
    - env: HASS='--pre homeassistant'

before_install:
  - mv .travis/travis_secrets.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - HA_VERSION=$(<.HA_VERSION)

install:
  - pip3 install $HASS
  - pip3 install colorlog

script:
  - hass -c . --script check_config --info all
