dist: xenial:latest

language: python
python:
  - "3.7"

env:
  - HASS='homeassistant'
  - HASS='--pre homeassistant'
  
matrix:
  allow_failures: 
    - python: "latest"
    - env: HASS='--pre homeassistant'

before_install:
  - mv .secrets/secrets.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log

install:
  - pip3 install $HASS
  - pip3 install colorlog

script:
  - hass -c . --script check_config --info all

after_success:
  - HA_VERSION=$(<.HA_VERSION)
  - echo this configuration is valid in Home Assistant $HA_VERSION