- id: '1561220695968'
  alias: Verlichting; aan; veranda garage carport
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      entity_id:
      - light.veranda_garage
      - light.carport_en_co
    service: light.turn_on
- id: '1564754408874'
  alias: Verlichting; uit; veranda garage carport
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id:
      - light.veranda_garage
      - light.carport_en_co
    service: light.turn_off
- id: '1570943721479'
  alias: Nieuwe automatisering
  description: ''
  trigger:
  - at: 03:00:00
    platform: time
  condition: []
  action:
  - service: hassio.snapshot_full
