- id: '1561220695968'
  alias: Verlichting; aan; veranda garage carport; zonsondergang
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      entity_id:
      - light.veranda_garage
      - light.carport_en_co
    service: light.turn_on
- id: '1564754408874'
  alias: Verlichting; uit; veranda garage carport; zonsopkomst
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id:
      - light.veranda_garage
      - light.carport_en_co
    service: light.turn_off
- id: '1570943721479'
  alias: dagelijks snapschot; volledig hass.io; 03:00
  description: ''
  trigger:
  - at: 03:00:00
    platform: time
  condition: []
  action:
  - service: hassio.snapshot_full
- id: '1571249904897'
  alias: ledstrips standaard; bureau zolder, plafond zolder; conditioneel
  description: ''
  trigger:
  - entity_id: light.bureau_verlichting
    from: unavailable
    platform: state
  - entity_id: light.plafond_verlichting
    from: unavailable
    platform: state
  condition: []
  action:
  - data:
      brightness_pct: 60
      entity_id:
      - light.plafond_verlichting
      - light.bureau_verlichting
      rgb_color:
      - 255
      - 212
      - 212
    service: light.turn_off
- id: '1571334543594'
  alias: GitHub Actions pass; Pull config; hass.io
  description: GitHub webhook voor het controleren van de CI status van config updates.
  trigger:
  - platform: webhook
    webhook_id: GitHub_webhook
  condition: []
  action: []
