################################################################################
# Home Assistant Configuration
################################################################################

default_config:

homeassistant:
  packages: !include_dir_named packages

frontend: 
  themes: !include_dir_merge_named themes

automation: !include automations.yaml

#customize: !include customize.yaml