---
########################
# Home Assistant Configuration#
########################

default_config:

homeassistant:
  packages: !include_dir_named packages

automation: !include automations.yaml
script: !include scripts.yaml
