################################################################################
# Home Assistant Configuration
################################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

customize: !include customize.yaml

packages: !include_dir_named packages