################################################################################
# Home Assistant Configuration
################################################################################

homeassistant:
  name: Thuis

default_config:

customize: !include customize.yaml

packages: !include_dir_named packages