################################################################################
# Home Assistant Configuration
################################################################################

default_config:

homeassistant:
  packages: !include_dir_named packages

automation: !include automations.yaml
frontend: themes: !include_dir_merge_named themes
#customize: !include customize.yaml