---
sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: ipv4_address
        arg: ovs_eth0
      - type: ipv4_address
        arg: ovs_eth1
      - type: processor_use
      - type: last_boot
