media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_key
    aliases:
        abc123def456: 'Living Room'
        9183abas000: 'Bed Room'

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

sensor:
  - platform: spotcast