---
### This file contains all default settings for 
### the RFLink hub, which uses MHz443
### to wirelessly control devices

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__USBDevice_85633323530351C0E162-if00
  ignore_devices:
  - newkaku_00bb8f36*
  - tristate_088aaa*
  - bft_1003c*
  - doorbell_00011c4e*
  - doorbell_08b1*
  - drayton_e000*
  - brelmotor_2f00ab*
  - chuango_5d80*
  - chuango_0696*
  - chuango_bc6f*
  - selectplus_034b*
  - mertik_gv60_022c4*

switch:
  - platform: rflink
    device_defaults:
      signal_repetitions: 3

light:
  - platform: rflink
    automatic_add: true
    device_defaults:
      signal_repetitions: 3

cover:
  - platform: rflink
    device_defaults:
      signal_repetitions: 3

sensor:
  - platform: rflink
    automatic_add: true

discovery: