---
id: '1561220695968'
alias: Verlichting; aan; veranda garage carport; zonsondergang
trigger:
  - event: sunset
    platform: sun
condition: []
action:
  - data:
    entity_id:
      - light.veranda_garage
      - light.carport_en_co
    service: light.turn_on
