---
substitutions:
  device: esp32oled0001
  name: Test oled
  description: 
  reboot_timeout: 14d
  update_interval: 10min

esphome:
  name: ${device}
  comment: ${description}
  platform: ESP32
  board: heltec_wifi_kit_32

<<: !include  common/common.yaml
<<: !include common/sensors.yaml
logger:

i2c:
  sda: 4
  scl: 15

time:
  - platform: homeassistant
    id: hatime

sensor:
  - platform: homeassistant
    id: polution_level
    entity_id: sensor.u_s_air_pollution_level
    internal: true

  - platform: homeassistant
    id: primary_polutant
    entity_id: sensor.u_s_main_pollutant
    internal: true

font:
  - file: "fonts/OpenSans-Regular.ttf"
    id: opensans
    size: 14
    
  - file: "fonts/Montserrat-Regular.ttf"
    id: montserrat
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 16
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(opensans), "Hello World!");
