---
substitutions:
  device: filamentsensor0001
  name: filament box 1
  description: omgevingssensor bovenste filament box
  reboot_timeout: 14d
  update_interval: 10min

esphome:
  name: ${device}
  comment: ${description}
  platform: ESP8266
  board: d1_mini

<<: !include common/common.yaml
<<: !include common/sensors.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensors.yaml

deep_sleep:
  run_duration: 120min
  sleep_duration: 1min

i2c:

sensor:
  - platform: bme280
    temperature:
      name: ${device} Temperature
      oversampling: 8x
    pressure:
      name: ${device} Pressure
      oversampling: 8x
    humidity:
      name: ${device} Humidity
    address: 0x76
    update_interval: 20s
    iir_filter: 4x

  - platform: adc
    pin: VCC
    name: ${device} VCC Voltage
    
