---
substitutions:
  device: filamentsensor0001
  name: bureau verlichting
  description: ledstrip onder monitor bureau, zolder
  reboot_timeout: 14d
  update_interval: 10min

esphome:
  name: ${device}
  comment: ${description}
  platform: ESP8266
  board: esp01_1m

  on_boot:
    priority: -500
    then:
      - light.turn_on:
          id: led0000
          brightness: 65%
          red: 1
          green: 0.824
          blue: 0.824
          
      - light.turn_off: led0000

<<: !include common/common.yaml
<<: !include common/sensors.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensors.yaml

light:
  - platform: rgb
    name: "bureau verlichting"
    id: led0000
    default_transition_length: 3s
    red: output_component1
    green: output_component2
    blue: output_component3

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: 14
  - platform: esp8266_pwm
    id: output_component2
    pin: 5
  - platform: esp8266_pwm
    id: output_component3
    pin: 12
