---
substitutions:
  device: filamentsensor0002
  name: plafond verlichting
  description: ledstrips achter de dwarsbalken, zolder
  reboot_timeout: 14d
  update_interval: 10min

esphome:
  name: ${device}
  comment: ${description}
  platform: ESP8266
  board: esp01_1m

  on_boot:
    priority: -500
    then:
      - light.turn_on:
          id: led0002
          brightness: 55%
          red: 1
          green: 0.824
          blue: 0.824
          
      - light.turn_off: led0002

<<: !include common/common.yaml
<<: !include common/sensors.yaml
logger:

light:
  - platform: rgb
    name: ${name}
    id: led0002
    default_transition_length: 3s
    red: output_component1
    green: output_component2
    blue: output_component3

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: 5
  - platform: esp8266_pwm
    id: output_component2
    pin: 12
  - platform: esp8266_pwm
    id: output_component3
    pin: 13

binary_sensor:
  - platform: status
    name: ${device} status
