device_tracker:
  - platform: upc_connect
    host: !secret connectbox
    password: !secret connectbox_password
  
owntracks:
  max_gps_accuracy: 1000
  waypoints: false
  events_only: false

sensor:
  - platform: template
    sensors:
      noodles_mood:
        friendly_name: Noodles
        icon_template: mdi:dog
        entity_id: sensor.beat
        value_template: >-
          {#- static input -#}
          {% set static = (([{"Noodles":0,"output":["","","","","",""]},{"Noodles":1,"output":["","Spook? 👻","","","",""]},{"Noodles":2,"output":["","","","","",""]},{"Noodles":3,"output":["","","Hallo? ⁉","","",""]},{"Noodles":4,"output":["","","","","",""]},{"Noodles":5,"output":["","","","","SPIN!¡? 🕷",""]},{"Noodles":6,"output":["","","","","","Gaap! 🥱"]},{"Noodles":7,"output":["","","","","Koekje! 🍪",""]},{"Noodles":8,"output":["","","","","Rondje! 🏃","Rondje! 🏃"]},{"Noodles":9,"output":["Eten? 🍖'","Eten? 🍖'","","Kaas! 🧀","",""]},{"Noodles":10,"output":["","","Kaas! 🧀","","","Kip? 🐔"]},{"Noodles":11,"output":["Koekje! 🍪","","","","",""]},{"Noodles":12,"output":["","Kaas! 🧀","Koekje! 🍪","","","Kaas! 🧀"]},{"Noodles":13,"output":["Rondje! 🏃","Rondje! 🏃","Rondje! 🏃","Eten? 🍖'","Eten? 🍖'",""]},{"Noodles":14,"output":["","BLAF 😡","","","",""]},{"Noodles":15,"output":["","Kip? 🐔","","","",""]},{"Noodles":16,"output":["TOUWTJE!!! 🧶","TOUWTJE!!! 🧶","TOUWTJE!!! 🧶","TOUWTJE!!! 🧶","",""]},{"Noodles":17,"output":["","","","","",""]},{"Noodles":18,"output":["","Koekje! 🍪","","","",""]},{"Noodles":19,"output":["Rondje! 🏃","Rondje! 🏃","Rondje! 🏃","","Eten? 🍖'","Eten? 🍖'"]},{"Noodles":20,"output":["","","","","Koekje! 🍪",""]},{"Noodles":21,"output":["TOUWTJE!!! 🧶","TOUWTJE!!! 🧶","","","",""]},{"Noodles":22,"output":["","","","","",""]},{"Noodles":23,"output":["","Koekje! 🍪","","","TOUWTJE!!! 🧶","TOUWTJE!!! 🧶"]}])) %}

          {#- Input from HA -#}
          {% set bed_time = states('input_number.bed_hour')|float(23) %}
          {% set wakeup_time = states('input_number.wakeup_hour')|float(7) %}
          {% set persons = states.person %}

          {#- Native functions -#}
          {% set hour = now().hour|int %}
          {% set minute = now().minute|int %}

          {% set person_state = 'home' %}
          {% set night = false if hour in range(wakeup_time,bed_time) else true %}
          {% set anyone_here|d([]) -%}
          {% set pipe = joiner(', ') -%}
          {% for person in persons %}{{ pipe() -}}
          {{ person.state }}{% endfor %}{% endset -%}
          {% set someone_here = true, [anyone_here] if person_state in anyone_here else false %}

          {% set x = static[now().hour].output[now().minute/10|round(0,floor)|int] %}

          {% if x %}
          {{ x }}
          {% elif someone_here and not night %}
          {{ 'spelen? 🥎' }}
          {% else %}
          {{ 'Zzz 😴' }}
          {% endif %}
