device_tracker:
  - platform: upc_connect
    host: !secret connectbox
    password: !secret connectbox_password
  
owntracks:
  max_gps_accuracy: 1000
  waypoints: false
  events_only: false

sensor:
  - platform: template
    sensors:
      noodles_mood:
        friendly_name: Noodles
        icon_template: mdi:dog
        entity_id: sensor.beat
        value_template: >-
          {% set bed_time = states('input_number.bed_hour')|float(23) %}
          {% set wakeup_time = states('input_number.wakeup_hour')|float(7) %}
          {% set night = false if now().hour in range(wakeup_time,bed_time) else true %}

          {% set anyone_home %}
            {% set pipe = joiner(', ') %}
            {% for person in states.person %} {{ pipe() }}
              {{ person.state }}
          {% endfor %}{% endset %}
          {% set someone_home = true if 'home' in anyone_home else false %}

          {% set output = 'spelen? 🥎' if someone_home and not night else 'Zzz 😴' %}

          {{ output|default('') }}
        attribute_templates: 
          outputs: >-
            {'day': [['Eten? \U0001F356', [[9,0,20],[14,10,20],[19,0]]], ['Koekje! \U0001F36A',[[16,40,0,0x0010010],[14,30,10,0x1000100]]], 'Rondje! \U0001f3c3', 'Kip? \U0001f414', 'Kaas! \U0001f9c0', TOUWTJE!!! \U0001f9f6', 'BLAF \U0001f621', 'spelen? \U0001f94e'], 'night': ['Zzz \U0001f4a4', 'Spook? \U0001f47b', 'SPIN!¡? \U0001f577', 'Hallo? \U0001f415']}
          schedule: >-
            {
              "0": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "1": {
                "0": "",
                "10": "Spook? \U0001f47b",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "2": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "3": {
                "0": "",
                "10": "",
                "20": "Hallo? \U0001f415",
                "30": "",
                "40": "",
                "50": ""
              },
              "4": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "5": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "SPIN!¡? \U0001f577",
                "50": ""
              },
              "6": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "7": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "Koekje! \U0001F36A",
                "50": ""
              },
              "8": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "Rondje! \U0001f3c3",
                "50": "Rondje! \U0001f3c3"
              },
              "9": {
                "0": "Eten? \U0001F356'",
                "10": "Eten? \U0001F356'",
                "20": "",
                "30": "Kaas! \U0001f9c0",
                "40": "",
                "50": ""
              },
              "10": {
                "0": "",
                "10": "",
                "20": "Kaas! \U0001f9c0",
                "30": "",
                "40": "",
                "50": "Kip? \U0001f414"
              },
              "11": {
                "0": "Koekje! \U0001F36A",
                "10": "",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "12": {
                "0": "",
                "10": "Kaas! \U0001f9c0",
                "20": "Koekje! \U0001F36A",
                "30": "",
                "40": "",
                "50": "Kaas! \U0001f9c0"
              },
              "13": {
                "0": "Rondje! \U0001f3c3",
                "10": "Rondje! \U0001f3c3",
                "20": "Rondje! \U0001f3c3",
                "30": "Eten? \U0001F356'",
                "40": "Eten? \U0001F356'",
                "50": ""
              },
              "14": {
                "0": "",
                "10": "BLAF \U0001f621",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "15": {
                "0": "",
                "10": "Kip? \U0001f414",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "16": {
                "0": "TOUWTJE!!! \U0001f9f6",
                "10": "TOUWTJE!!! \U0001f9f6",
                "20": "TOUWTJE!!! \U0001f9f6",
                "30": "TOUWTJE!!! \U0001f9f6",
                "40": "",
                "50": ""
              },
              "17": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "18": {
                "0": "",
                "10": "Koekje! \U0001F36A",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "19": {
                "0": "Rondje! \U0001f3c3",
                "10": "Rondje! \U0001f3c3",
                "20": "Rondje! \U0001f3c3",
                "30": "",
                "40": "Eten? \U0001F356'",
                "50": "Eten? \U0001F356'"
              },
              "20": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "Koekje! \U0001F36A",
                "50": ""
              },
              "21": {
                "0": "TOUWTJE!!! \U0001f9f6",
                "10": "TOUWTJE!!! \U0001f9f6",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "22": {
                "0": "",
                "10": "",
                "20": "",
                "30": "",
                "40": "",
                "50": ""
              },
              "23": {
                "0": "",
                "10": "Koekje! \U0001F36A",
                "20": "",
                "30": "",
                "40": "TOUWTJE!!! \U0001f9f6",
                "50": "TOUWTJE!!! \U0001f9f6"
              }
            }
                        
