device_tracker:
  - platform: upc_connect
    host: !secret connectbox
    password: !secret connectbox_password
  
owntracks:
  max_gps_accuracy: 1000
  waypoints: false
  events_only: false

sensor:
  - platform: template
    sensors:
      noodles_mood:
        friendly_name: Noodles
        icon_template: mdi:dog
        entity_id: sensor.beat
        value_template: >-
          {% set bed_time = states('input_number.bed_hour')|float(23) %}
          {% set wakeup_time = states('input_number.wakeup_hour')|float(7) %}
          {% set night = false if now().hour in range(wakeup_time,bed_time) else true %}

          {% set anyone_home %}
            {% set pipe = joiner(', ') %}
            {% for person in states.person %} {{ pipe() }}
              {{ person.state }}
          {% endfor %}{% endset %}
          {% set someone_home = true if 'home' in anyone_home else false %}

          {% set output = 'spelen? 🥎' if someone_home and not night else 'Zzz 😴' %}

          {{ output|default('') }}
        attribute_templates: 
          outputs:
            day: >
              ['Eten? \U0001F356', [[9,0,20],[14,10,20],[19,0]]], ['Koekje! \U0001F36A',[[16,40,0,0x0010010],[14,30,10,0x1000100]]], 'Rondje! \U0001f3c3', 'Kip? 🐔',, 'Kaas! 🧀', 'TOUWTJE!!! 🧶', 'BLAF 😡📢', 'spelen? 🥎' 
            night: >
              'Zzz 😴', 'Spook? 👻', 'SPIN!¡? 🕷', 'Hallo? 🐕‍🦺'