---
homeassistant:
  latitude: !secret lat
  longitude: !secret long
  elevation: 17
  unit_system: metric
  time_zone: CET
#  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named ../../themes/

http:
  base_url: !secret base_url
  # ip_ban_enabled:  true
  # login_attempts_threshold: 5

### Text to speech is used to enable Google Home to relay information via a spoken message ###
tts:
  - platform: google_translate
    language: 'nl'
    base_url: !secret base_url

system_health:
