---
name: Home Assistant

on: [push, pull_request]

jobs:
  test:
    name: Home Assistant ${{matrix.release}}
    runs-on: ubuntu-18.04
    container: docker://homeassistant/home-assistant:${{matrix.release}}
    strategy:
      matrix:
        release: ['stable', 'rc', 'dev']

    steps:
      - name: pull config from GitHub repo
        uses: actions/checkout@v1
      - name: move redacted secrets and check Home Assistant version
        run: |
          cp -R ./.secrets/* ./
      - name: Home Assistant version
        id: version_check
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: |
          python -m homeassistant --version >> ./.HA_TEST
          echo "$STEPS_CONTEXT"
      - name: Home Assistant:stable config check
        id: config_check
        if: matrix.release == 'stable' || ( matrix.release != 'stable' && ./.HA_TEST != ./.HA_VERSION )
        run: |
          python -m homeassistant --config ./ --script check_config --info all
      - name: POST to production to pull new build
        if: success()
        run: |
          curl -X POST \
          --url ${{ secrets.WEBHOOK_URL }} \
          --header 'content-type: application/json' \
          --data '{ "build": "success" }'
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
