---
name: Home Assistant
#insert linters someday

on:
  push:
  pull_request:

jobs:
  home_assistant:
    runs-on: ubuntu-latest
    steps:
      - name: pull config from GitHub repo
        uses: actions/checkout@v1
      - name: move redacted secrets
        run: cp -R ./.secrets/* ./
      - name: Home Assistant version
        uses: 'docker://homeassistant/home-assistant:stable'
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant config check
        uses: 'docker://homeassistant/home-assistant:stable'
        with:
          args: python -m homeassistant --config ./ --script check_config --info all
      - name: POST to production to pull new build
        if: success()
        run: |
          curl -X POST \
          --url ${{ secrets.WEBHOOK_URL }} \
          --header 'content-type: application/json' \
          --data '{ "build": "success" }'
  home_assistant_beta:
    runs-on: ubuntu-latest
    steps:
      - name: pull config from GitHub repo
        uses: actions/checkout@v1
      - name: move redacted secrets
        run: cp -R ./.secrets/* ./
      - name: Home Assistant version
        uses: 'docker://homeassistant/home-assistant:beta'
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant config check
        uses: 'docker://homeassistant/home-assistant:beta'
        with:
          args: python -m homeassistant --config ./ --script check_config --info all
  home_assistant_dev:
    runs-on: ubuntu-latest
    steps:
      - name: pull config from GitHub repo
        uses: actions/checkout@v1
      - name: move redacted secrets
        run: cp -R ./.secrets/* ./
      - name: Home Assistant version
        uses: 'docker://homeassistant/home-assistant:dev'
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant config check
        uses: 'docker://homeassistant/home-assistant:dev'
        with:
          args: python -m homeassistant --config ./ --script check_config --info all
