---
name: Home Assistant

on: [push, pull_request]

jobs:
  test:
    name: Home Assistant ${{ matrix.release }}
    runs-on: ubuntu-18.04
    container: docker://homeassistant/home-assistant:${{ matrix.release }}
    strategy:
      matrix:
        release: ['stable', 'rc', 'dev']

    steps:
      - name: pull config from GitHub repo
        uses: actions/checkout@v1

      - name: Home Assistant version
        id: version_check
        run: |
          echo ::set-output name=homeassistant_version::$( python -m homeassistant --version )
          echo ::set-output name=config_version::$( cat .HA_VERSION )

      - name: move redacted secrets
        run: |
          cp -R ./.secrets/* ./

      - name: test config against ${{ matrix.release }} release
        if: matrix.release == 'stable' || steps.version_check.outputs.homeassistant_version != steps.version_check.outputs.config_version
        run: |
          python -m homeassistant --config ./ --script check_config --info all

      - name: inform production container to pull
        if: success() && matrix.release == 'stable'
        run: |
          curl -X POST \
          --url ${{ secrets.WEBHOOK_URL }} \
          --header 'content-type: application/json' \
          --data '${{ job }}'

      - run: |
          echo +refs/heads/*:refs/remotes/origin/*
