---
name: Home Assistant

on: [push, pull_request]

jobs:
  test:
    name: Home Assistant ${{matrix.release}}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        release: ['stable', 'rc', 'dev']
    
    steps:
    - name: pull config from GitHub repo
      uses: actions/checkout@v1
    - name: move redacted secrets
      run: cp -R ./.secrets/* ./
    - name: Home Assistant ${{matrix.release}} version
      uses: docker://homeassistant/home-assistant:${{matrix.release}}
      with:
        args: |
          python -m homeassistant --version
    - name: Home Assistant ${{matrix.release}} config check
      uses: docker://homeassistant/home-assistant:${{matrix.release}}
      with:
        args: python -m homeassistant --config ./ --script check_config --info all
    - name: POST to production to pull new build
      if: success()
      run: |
        curl -X POST \
        --url ${{ secrets.WEBHOOK_URL }} \
        --header 'content-type: application/json' \
        --data '{ "build": "success" }'
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"



  # home_assistant-rc:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: pull config from GitHub repo
  #       uses: actions/checkout@v1
  #     - name: move redacted secrets
  #       run: cp -R ./.secrets/* ./
  #     - name: Home Assistant version
  #       uses: 'docker://homeassistant/home-assistant:rc'
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant config check
  #       uses: 'docker://homeassistant/home-assistant:rc'
  #       with:
  #         args: python -m homeassistant --config ./ --script check_config --info all
  # home_assistant_beta:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: pull config from GitHub repo
  #       uses: actions/checkout@v1
  #     - name: move redacted secrets
  #       run: cp -R ./.secrets/* ./
  #     - name: Home Assistant version
  #       uses: 'docker://homeassistant/home-assistant:beta'
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant config check
  #       uses: 'docker://homeassistant/home-assistant:beta'
  #       with:
  #         args: python -m homeassistant --config ./ --script check_config --info all
  # home_assistant_latest:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: pull config from GitHub repo
  #       uses: actions/checkout@v1
  #     - name: move redacted secrets
  #       run: cp -R ./.secrets/* ./
  #     - name: Home Assistant version
  #       uses: 'docker://homeassistant/home-assistant:latest'
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant config check
  #       uses: 'docker://homeassistant/home-assistant:latest'
  #       with:
  #         args: python -m homeassistant --config ./ --script check_config --info all
  # home_assistant_dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: pull config from GitHub repo
  #       uses: actions/checkout@v1
  #     - name: move redacted secrets
  #       run: cp -R ./.secrets/* ./
  #     - name: Home Assistant version
  #       uses: 'docker://homeassistant/home-assistant:dev'
  #       with:
  #         args: |
  #           python -m homeassistant --version
  #     - name: Home Assistant config check
  #       uses: 'docker://homeassistant/home-assistant:dev'
  #       with:
  #         args: python -m homeassistant --config ./ --script check_config --info all
