name: Validate Home Assistant config

on: push

jobs: 
  validate_config:
    name: Validate with current stable release
    runs-on: ubuntu-18.04
    steps:
    - name: Cloning config to testing environment
      uses: actions/checkout@v1
    - name: Run Home Assistant in Docker
      env:
        VERSION: latest
      run: docker run --init -d --name="home-assistant" -e "TZ=America/New_York" -v /$GITHUB_WORKSPACE:/config --net=host homeassistant/home-assistant:$VERSION
    - name: Check config
      run: hass --script check_config --info all
