name: Validate Home Assistant config

on: push

jobs: 
  validate_config:
    name: Validate with current stable release
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Validate config with current stable release
      uses: ./.actions
