name: Validate Home Assistant config

on: push

jobs: 
  validate_config:
    name: Validate with current stable release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Validate config with current stable release
      uses: ./.actions
