name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: POST to production to pull new build
      if: succes()
      run: |
        curl -X POST \
        --url ${{ secrets.WEBHOOK_URL }} \
        --header 'content-type: application/json' \
        --data '{ "build": "success" }'
